VLLM_API_KEY: test
VLLM_OPENAI_ENDPOINT: your_vllm_endpoint
TOGETHER_API_KEY: your_together_api_key
ANTHROPIC_API_KEY: your_anthropic_api_key
GOOGLE_API_KEY: your_google_api_key
AZURE_OPENAI_KEY: your_azure_openai_api_key
AZURE_OPENAI_ENDPOINT: your_azure_openai_endpoint
AZURE_OPENAI_KEY_GPT4: your_azure_openai_api_key
AZURE_OPENAI_ENDPOINT_GPT4: your_azure_openai_endpoint
AZURE_OPENAI_KEY_GPT4O: your_azure_openai_api_key
AZURE_OPENAI_ENDPOINT_GPT4O: your_azure_openai_endpoint
ZHIPU_API_KEY: your_zhipu_api_key
WENXIN_API_KEY: your_wenxin_api_key
WENXIN_SECRET_KEY: your_wenxin_secret_key
MINIMAX_API_KEY: your_minimax_api_key
SENSECHAT_API_KEY: your_sensechat_api_key
SENSECHAT_SECRET_KEY: your_sensechat_secret_key
BAICHUAN_API_KEY: your_baichuan_api_key
REKA_API_KEY: your_reka_api_key
MISTRAL_API_KEY: your_mistral_api_key
COHERE_API_KEY: your_cohere_api_key
OPENAI_API_KEY: your_openai_api_key

